services:
    database:
        image: postgres
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: pass
    backend:
        build:
            context: PracticeTrackerAPI/
            dockerfile: Dockerfile
        ports:
            - 10000:8080
        environment:
            ASPNETCORE_ENVIRONMENT: Production
        depends_on:
            - database
