services:
    database:
        image: postgres
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: pass
    backend:
        build:
            context: PracticeTrackerAPI/
            dockerfile: Dockerfile
        ports:
            - 10000:8080
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            POSTGRES_CONNECTION_STRING: Server=database;Port=5432;Username=postgres;Password=pass;Database=sessions
            MIGRATE_MANUALLY: true
            USE_SWAGGER_UI: true
        depends_on:
            - database
